/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lucas
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Calculator
     */
    public Calculator() {
       
        initComponents();
    }
    double v1;
    double v2;
    String operation;
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        answerField1 = new javax.swing.JTextField();
        button_times1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        button_1 = new javax.swing.JButton();
        button_2 = new javax.swing.JButton();
        button_4 = new javax.swing.JButton();
        button_5 = new javax.swing.JButton();
        button_3 = new javax.swing.JButton();
        button_8 = new javax.swing.JButton();
        button_9 = new javax.swing.JButton();
        button_0 = new javax.swing.JButton();
        button_dot = new javax.swing.JButton();
        button_equals = new javax.swing.JButton();
        button_plus = new javax.swing.JButton();
        button_6 = new javax.swing.JButton();
        button_division = new javax.swing.JButton();
        button_minus = new javax.swing.JButton();
        button_close_parenthesis = new javax.swing.JButton();
        button_open_parenthesis = new javax.swing.JButton();
        button_times = new javax.swing.JButton();
        button_7 = new javax.swing.JButton();
        operationBox = new javax.swing.JTextField();
        resultBox = new javax.swing.JTextField();
        button_exp = new javax.swing.JButton();
        button_pi = new javax.swing.JButton();
        button_sqr = new javax.swing.JButton();
        button_c = new javax.swing.JButton();
        button_fat = new javax.swing.JButton();
        button_easterEgg = new javax.swing.JButton();

        jButton4.setBackground(new java.awt.Color(51, 51, 51));
        jButton4.setText("jButton2");

        jButton8.setBackground(new java.awt.Color(51, 51, 51));
        jButton8.setText("jButton2");

        jButton11.setBackground(new java.awt.Color(51, 51, 51));
        jButton11.setText("jButton2");

        jButton14.setBackground(new java.awt.Color(51, 51, 51));
        jButton14.setText("jButton2");

        jButton16.setBackground(new java.awt.Color(51, 51, 51));
        jButton16.setText("jButton2");

        jButton20.setBackground(new java.awt.Color(51, 51, 51));
        jButton20.setText("jButton2");

        jButton23.setBackground(new java.awt.Color(51, 51, 51));
        jButton23.setText("jButton2");

        jButton26.setBackground(new java.awt.Color(51, 51, 51));
        jButton26.setText("/");

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jButton28.setBackground(new java.awt.Color(51, 51, 51));
        jButton28.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        jButton28.setForeground(new java.awt.Color(255, 255, 255));
        jButton28.setText("1");

        jButton29.setBackground(new java.awt.Color(51, 51, 51));
        jButton29.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        jButton29.setForeground(new java.awt.Color(255, 255, 255));
        jButton29.setText("2");

        jButton30.setBackground(new java.awt.Color(51, 51, 51));
        jButton30.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        jButton30.setForeground(new java.awt.Color(255, 255, 255));
        jButton30.setText("4");

        jButton31.setBackground(new java.awt.Color(51, 51, 51));
        jButton31.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        jButton31.setForeground(new java.awt.Color(255, 255, 255));
        jButton31.setText("5");

        jButton32.setBackground(new java.awt.Color(51, 51, 51));
        jButton32.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        jButton32.setForeground(new java.awt.Color(255, 255, 255));
        jButton32.setText("3");

        jButton33.setBackground(new java.awt.Color(51, 51, 51));
        jButton33.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        jButton33.setForeground(new java.awt.Color(255, 255, 255));
        jButton33.setText("8");

        jButton34.setBackground(new java.awt.Color(51, 51, 51));
        jButton34.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        jButton34.setForeground(new java.awt.Color(255, 255, 255));
        jButton34.setText("9");

        jButton35.setBackground(new java.awt.Color(51, 51, 51));
        jButton35.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        jButton35.setForeground(new java.awt.Color(255, 255, 255));
        jButton35.setText("0");

        jButton36.setBackground(new java.awt.Color(51, 51, 51));
        jButton36.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        jButton36.setForeground(new java.awt.Color(255, 255, 255));
        jButton36.setText(".");

        jButton37.setBackground(new java.awt.Color(255, 215, 0));
        jButton37.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        jButton37.setForeground(new java.awt.Color(0, 0, 0));
        jButton37.setText("=");

        jButton38.setBackground(new java.awt.Color(51, 51, 51));
        jButton38.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        jButton38.setForeground(new java.awt.Color(255, 255, 255));
        jButton38.setText("+");

        jButton39.setBackground(new java.awt.Color(51, 51, 51));
        jButton39.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        jButton39.setForeground(new java.awt.Color(255, 255, 255));
        jButton39.setText("6");

        jButton40.setBackground(new java.awt.Color(51, 51, 51));
        jButton40.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        jButton40.setForeground(new java.awt.Color(255, 255, 255));
        jButton40.setText("*");

        jButton41.setBackground(new java.awt.Color(51, 51, 51));
        jButton41.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        jButton41.setForeground(new java.awt.Color(255, 255, 255));
        jButton41.setText("-");

        jButton42.setBackground(new java.awt.Color(51, 51, 51));
        jButton42.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        jButton42.setForeground(new java.awt.Color(255, 255, 255));
        jButton42.setText("/");

        jButton43.setBackground(new java.awt.Color(51, 51, 51));
        jButton43.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        jButton43.setForeground(new java.awt.Color(255, 255, 255));
        jButton43.setText("7");

        jButton44.setBackground(new java.awt.Color(51, 51, 51));
        jButton44.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        jButton44.setForeground(new java.awt.Color(255, 255, 255));
        jButton44.setText("7");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jButton43, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton42, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton40, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButton35, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton36, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton30, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton28, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton44, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton29, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton32, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton37, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton31, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton39, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton38, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton33, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton34, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton41, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 118, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton40, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton42, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton43, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton33, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton34, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton41, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton44, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton30, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton31, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton39, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton38, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton28, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton29, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton32, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton35, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton36, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton37, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        answerField1.setBackground(new java.awt.Color(0, 0, 0));
        answerField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        answerField1.setText("jTextField1");
        answerField1.setBorder(null);
        answerField1.setOpaque(false);
        answerField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerField1ActionPerformed(evt);
            }
        });

        button_times1.setBackground(new java.awt.Color(51, 51, 51));
        button_times1.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        button_times1.setForeground(new java.awt.Color(255, 255, 255));
        button_times1.setText("*");
        button_times1.setBorder(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        button_1.setBackground(new java.awt.Color(51, 51, 51));
        button_1.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        button_1.setForeground(new java.awt.Color(255, 255, 255));
        button_1.setText("1");
        button_1.setBorder(null);
        button_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_1ActionPerformed(evt);
            }
        });

        button_2.setBackground(new java.awt.Color(51, 51, 51));
        button_2.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        button_2.setForeground(new java.awt.Color(255, 255, 255));
        button_2.setText("2");
        button_2.setBorder(null);
        button_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_2ActionPerformed(evt);
            }
        });

        button_4.setBackground(new java.awt.Color(51, 51, 51));
        button_4.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        button_4.setForeground(new java.awt.Color(255, 255, 255));
        button_4.setText("4");
        button_4.setBorder(null);
        button_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_4ActionPerformed(evt);
            }
        });

        button_5.setBackground(new java.awt.Color(51, 51, 51));
        button_5.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        button_5.setForeground(new java.awt.Color(255, 255, 255));
        button_5.setText("5");
        button_5.setBorder(null);
        button_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_5ActionPerformed(evt);
            }
        });

        button_3.setBackground(new java.awt.Color(51, 51, 51));
        button_3.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        button_3.setForeground(new java.awt.Color(255, 255, 255));
        button_3.setText("3");
        button_3.setBorder(null);
        button_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_3ActionPerformed(evt);
            }
        });

        button_8.setBackground(new java.awt.Color(51, 51, 51));
        button_8.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        button_8.setForeground(new java.awt.Color(255, 255, 255));
        button_8.setText("8");
        button_8.setBorder(null);
        button_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_8ActionPerformed(evt);
            }
        });

        button_9.setBackground(new java.awt.Color(51, 51, 51));
        button_9.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        button_9.setForeground(new java.awt.Color(255, 255, 255));
        button_9.setText("9");
        button_9.setBorder(null);
        button_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_9ActionPerformed(evt);
            }
        });

        button_0.setBackground(new java.awt.Color(51, 51, 51));
        button_0.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        button_0.setForeground(new java.awt.Color(255, 255, 255));
        button_0.setText("0");
        button_0.setBorder(null);
        button_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_0ActionPerformed(evt);
            }
        });

        button_dot.setBackground(new java.awt.Color(51, 51, 51));
        button_dot.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        button_dot.setForeground(new java.awt.Color(255, 255, 255));
        button_dot.setText(".");
        button_dot.setBorder(null);
        button_dot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_dotActionPerformed(evt);
            }
        });

        button_equals.setBackground(new java.awt.Color(255, 215, 0));
        button_equals.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        button_equals.setForeground(new java.awt.Color(0, 0, 0));
        button_equals.setText("=");
        button_equals.setBorder(null);
        button_equals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_equalsActionPerformed(evt);
            }
        });

        button_plus.setBackground(new java.awt.Color(51, 51, 51));
        button_plus.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        button_plus.setForeground(new java.awt.Color(255, 255, 255));
        button_plus.setText("+");
        button_plus.setBorder(null);
        button_plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_plusActionPerformed(evt);
            }
        });

        button_6.setBackground(new java.awt.Color(51, 51, 51));
        button_6.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        button_6.setForeground(new java.awt.Color(255, 255, 255));
        button_6.setText("6");
        button_6.setBorder(null);
        button_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_6ActionPerformed(evt);
            }
        });

        button_division.setBackground(new java.awt.Color(51, 51, 51));
        button_division.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        button_division.setForeground(new java.awt.Color(255, 255, 255));
        button_division.setText("/");
        button_division.setBorder(null);
        button_division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_divisionActionPerformed(evt);
            }
        });

        button_minus.setBackground(new java.awt.Color(51, 51, 51));
        button_minus.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        button_minus.setForeground(new java.awt.Color(255, 255, 255));
        button_minus.setText("-");
        button_minus.setBorder(null);
        button_minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_minusActionPerformed(evt);
            }
        });

        button_close_parenthesis.setBackground(new java.awt.Color(51, 51, 51));
        button_close_parenthesis.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        button_close_parenthesis.setForeground(new java.awt.Color(255, 255, 255));
        button_close_parenthesis.setText(")");
        button_close_parenthesis.setBorder(null);
        button_close_parenthesis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_close_parenthesisActionPerformed(evt);
            }
        });

        button_open_parenthesis.setBackground(new java.awt.Color(51, 51, 51));
        button_open_parenthesis.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        button_open_parenthesis.setForeground(new java.awt.Color(255, 255, 255));
        button_open_parenthesis.setText("(");
        button_open_parenthesis.setBorder(null);
        button_open_parenthesis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_open_parenthesisActionPerformed(evt);
            }
        });

        button_times.setBackground(new java.awt.Color(51, 51, 51));
        button_times.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        button_times.setForeground(new java.awt.Color(255, 255, 255));
        button_times.setText("x");
        button_times.setBorder(null);
        button_times.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_timesActionPerformed(evt);
            }
        });

        button_7.setBackground(new java.awt.Color(51, 51, 51));
        button_7.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        button_7.setForeground(new java.awt.Color(255, 255, 255));
        button_7.setText("7");
        button_7.setBorder(null);
        button_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_7ActionPerformed(evt);
            }
        });

        operationBox.setBackground(new java.awt.Color(0, 0, 0));
        operationBox.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 24)); // NOI18N
        operationBox.setForeground(new java.awt.Color(255, 255, 255));
        operationBox.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        operationBox.setBorder(null);
        operationBox.setOpaque(false);
        operationBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operationBoxActionPerformed(evt);
            }
        });

        resultBox.setBackground(new java.awt.Color(0, 0, 0));
        resultBox.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        resultBox.setForeground(new java.awt.Color(255, 255, 255));
        resultBox.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        resultBox.setBorder(null);
        resultBox.setOpaque(false);
        resultBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultBoxActionPerformed(evt);
            }
        });

        button_exp.setBackground(new java.awt.Color(51, 51, 51));
        button_exp.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        button_exp.setForeground(new java.awt.Color(255, 255, 255));
        button_exp.setText("exp");
        button_exp.setBorder(null);

        button_pi.setBackground(new java.awt.Color(51, 51, 51));
        button_pi.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        button_pi.setForeground(new java.awt.Color(255, 255, 255));
        button_pi.setText("π");
        button_pi.setBorder(null);
        button_pi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_piActionPerformed(evt);
            }
        });

        button_sqr.setBackground(new java.awt.Color(51, 51, 51));
        button_sqr.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        button_sqr.setForeground(new java.awt.Color(255, 255, 255));
        button_sqr.setText("√");
        button_sqr.setBorder(null);

        button_c.setBackground(new java.awt.Color(51, 51, 51));
        button_c.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        button_c.setForeground(new java.awt.Color(255, 255, 255));
        button_c.setText("C");
        button_c.setBorder(null);
        button_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_cActionPerformed(evt);
            }
        });

        button_fat.setBackground(new java.awt.Color(51, 51, 51));
        button_fat.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        button_fat.setForeground(new java.awt.Color(255, 255, 255));
        button_fat.setText("n!");
        button_fat.setBorder(null);
        button_fat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_fatActionPerformed(evt);
            }
        });

        button_easterEgg.setBackground(new java.awt.Color(0, 0, 0));
        button_easterEgg.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(resultBox, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(operationBox)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(button_0, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_dot, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(button_open_parenthesis, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(button_2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(button_3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(button_fat, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(button_pi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button_equals, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(button_5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button_6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button_plus, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button_sqr, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(button_close_parenthesis, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button_division, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button_times, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button_c, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(button_8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button_9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button_minus, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button_exp, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(button_easterEgg, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(button_easterEgg, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(operationBox, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(resultBox, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_division, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_close_parenthesis, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_open_parenthesis, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_times, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_c, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_8, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_9, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_minus, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_7, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_exp, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(button_4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_plus, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_sqr, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(button_1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_fat, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(button_0, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_dot, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_pi, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(button_equals, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void operationBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operationBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_operationBoxActionPerformed

    private void answerField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answerField1ActionPerformed

    private void resultBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultBoxActionPerformed

    private void button_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_0ActionPerformed
    operationBox.setText("");
        operationBox.setText(operationBox.getText()+"0");
    }//GEN-LAST:event_button_0ActionPerformed

    private void button_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_1ActionPerformed
        
        operationBox.setText(operationBox.getText()+"1");
        
    }//GEN-LAST:event_button_1ActionPerformed

    private void button_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_2ActionPerformed
       
        operationBox.setText(operationBox.getText()+"2");
                
    }//GEN-LAST:event_button_2ActionPerformed

    private void button_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_3ActionPerformed
      
        operationBox.setText(operationBox.getText()+"3");
                
    }//GEN-LAST:event_button_3ActionPerformed

    private void button_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_4ActionPerformed
       operationBox.setText(operationBox.getText()+"4");
              
    }//GEN-LAST:event_button_4ActionPerformed

    private void button_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_5ActionPerformed
        
        operationBox.setText(operationBox.getText()+"5");
                 
    }//GEN-LAST:event_button_5ActionPerformed

    private void button_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_6ActionPerformed
         
        operationBox.setText(operationBox.getText()+"6");
                 
    }//GEN-LAST:event_button_6ActionPerformed

    private void button_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_7ActionPerformed
        
        operationBox.setText(operationBox.getText()+"7");
                 
    }//GEN-LAST:event_button_7ActionPerformed

    private void button_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_8ActionPerformed
       
        operationBox.setText(operationBox.getText()+"8");
                
    }//GEN-LAST:event_button_8ActionPerformed

    private void button_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_9ActionPerformed
        
        operationBox.setText(operationBox.getText()+"9");
                 
    }//GEN-LAST:event_button_9ActionPerformed

    private void button_dotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_dotActionPerformed
        
        operationBox.setText(operationBox.getText()+".");
                
    }//GEN-LAST:event_button_dotActionPerformed

    private void button_open_parenthesisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_open_parenthesisActionPerformed
        
        operationBox.setText(operationBox.getText()+"(");
                 
    }//GEN-LAST:event_button_open_parenthesisActionPerformed

    private void button_close_parenthesisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_close_parenthesisActionPerformed
         
        operationBox.setText(operationBox.getText()+")");
                 
    }//GEN-LAST:event_button_close_parenthesisActionPerformed

    private void button_divisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_divisionActionPerformed
       operationBox.setText(operationBox.getText()+"/");
    }//GEN-LAST:event_button_divisionActionPerformed

    private void button_timesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_timesActionPerformed
         operationBox.setText(operationBox.getText()+"x");
    }//GEN-LAST:event_button_timesActionPerformed

    private void button_minusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_minusActionPerformed
        operationBox.setText(operationBox.getText()+"-");
    }//GEN-LAST:event_button_minusActionPerformed

    private void button_plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_plusActionPerformed
        
        v1=Double.parseDouble(operationBox.getText());
        operation="plus";
        operationBox.setText("");
        
    }//GEN-LAST:event_button_plusActionPerformed

    private void button_fatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_fatActionPerformed
        
    }//GEN-LAST:event_button_fatActionPerformed

    private void button_piActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_piActionPerformed
         operationBox.setText(operationBox.getText()+Math.PI);
    }//GEN-LAST:event_button_piActionPerformed

    private void button_equalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_equalsActionPerformed
        v2=Double.parseDouble(operationBox.getText());
        if(operation=="plus"){
            resultBox.setText(String.valueOf(v1+v2));
        }
    }//GEN-LAST:event_button_equalsActionPerformed

    private void button_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_cActionPerformed
        operationBox.setText("");
    }//GEN-LAST:event_button_cActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField answerField1;
    private javax.swing.JButton button_0;
    private javax.swing.JButton button_1;
    private javax.swing.JButton button_2;
    private javax.swing.JButton button_3;
    private javax.swing.JButton button_4;
    private javax.swing.JButton button_5;
    private javax.swing.JButton button_6;
    private javax.swing.JButton button_7;
    private javax.swing.JButton button_8;
    private javax.swing.JButton button_9;
    private javax.swing.JButton button_c;
    private javax.swing.JButton button_close_parenthesis;
    private javax.swing.JButton button_division;
    private javax.swing.JButton button_dot;
    private javax.swing.JButton button_easterEgg;
    private javax.swing.JButton button_equals;
    private javax.swing.JButton button_exp;
    private javax.swing.JButton button_fat;
    private javax.swing.JButton button_minus;
    private javax.swing.JButton button_open_parenthesis;
    private javax.swing.JButton button_pi;
    private javax.swing.JButton button_plus;
    private javax.swing.JButton button_sqr;
    private javax.swing.JButton button_times;
    private javax.swing.JButton button_times1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField operationBox;
    private javax.swing.JTextField resultBox;
    // End of variables declaration//GEN-END:variables
}
